### ISSUE TITLE
Document default values for size prop in VerticalLayout

### ISSUE THREAD

**Issue by bjornlexell** [einride/ui#242]
Suggestion: It would be nice to see which size that is the default value directly in the code. I think you could do something like this.

`export interface VerticalLayoutProps extends HTMLAttributes<HTMLDivElement> {
  as?: ElementType
  children: ReactNode
  /** Default value text goes here */
  size?: Size
}`

If this is something you want to add it could most likely be applied to other components as well

**Comment by filiptammergard** [comment]
Agreed! In the best of worlds we would have this kind of documentation for all props for all components. But a good start would be to add it for props that have default values.

**Comment by filiptammergard** [comment]
Assigning it to you @jenseo!

**Comment by jenseo** [comment]
First iteration of default values in this PR: #246
